import SwiftUI

/// The Aurora palette for kehdo iOS.
///
/// !!! GENERATED FROM /design/tokens/colors.json !!!
///
/// To update: edit the JSON, then run `./Scripts/generate-tokens.sh`.
/// Do not edit this file by hand — your changes will be overwritten.
///
/// (Hand-written placeholder for the scaffold; the generator will
/// overwrite the contents once wired up in Phase 0.)
public enum AuroraColors {
    public static let canvas = Color(red: 0.039, green: 0.024, blue: 0.071)        // #0A0612
    public static let surface = Color(red: 0.102, green: 0.059, blue: 0.180)       // #1A0F2E
    public static let surfaceElevated = Color(red: 0.141, green: 0.090, blue: 0.239) // #24173D

    public static let purple = Color(red: 0.612, green: 0.357, blue: 1.000)        // #9C5BFF
    public static let purpleBright = Color(red: 0.706, green: 0.482, blue: 1.000)  // #B47BFF
    public static let purpleDeep = Color(red: 0.420, green: 0.184, blue: 0.851)    // #6B2FD9

    public static let pink = Color(red: 0.925, green: 0.282, blue: 0.600)          // #EC4899
    public static let amber = Color(red: 0.961, green: 0.620, blue: 0.043)         // #F59E0B
    public static let blue = Color(red: 0.231, green: 0.510, blue: 0.965)          // #3B82F6
    public static let emerald = Color(red: 0.063, green: 0.725, blue: 0.506)       // #10B981

    public static let text = Color(red: 0.961, green: 0.953, blue: 1.000)          // #F5F3FF
    public static let textDim = Color(red: 0.961, green: 0.953, blue: 1.000).opacity(0.65)
    public static let textMute = Color(red: 0.961, green: 0.953, blue: 1.000).opacity(0.45)

    public static let line = Color.white.opacity(0.08)
    public static let lineStrong = Color.white.opacity(0.14)

    /// The signature Aurora gradient (purple → pink → amber, 135°).
    public static let gradient = LinearGradient(
        stops: [
            .init(color: purple, location: 0.0),
            .init(color: pink, location: 0.5),
            .init(color: amber, location: 1.0)
        ],
        startPoint: .topLeading,
        endPoint: .bottomTrailing
    )
}
