disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - multiline_arguments
  - sorted_imports
  - unused_import

excluded:
  - Packages/*/Sources/Generated
  - .build
  - DerivedData

line_length:
  warning: 130
  error: 160

force_unwrapping:
  severity: error

force_cast:
  severity: error

reporter: "xcode"
