package app.kehdo.core.network.api

import app.kehdo.core.network.api.dto.AuthResponseDto
import app.kehdo.core.network.api.dto.RefreshRequestDto
import app.kehdo.core.network.api.dto.SignInRequestDto
import app.kehdo.core.network.api.dto.SignUpRequestDto
import retrofit2.http.Body
import retrofit2.http.POST

/**
 * Retrofit binding for the /v1/auth endpoints — see
 * contracts/openapi/kehdo.v1.yaml. The full client is generated into
 * :core:network-generated by the openapi-generator Gradle plugin;
 * AuthApi is hand-written so PR 2 can land before that wiring.
 */
interface AuthApi {

    @POST("auth/signup")
    suspend fun signUp(@Body body: SignUpRequestDto): AuthResponseDto

    @POST("auth/login")
    suspend fun signIn(@Body body: SignInRequestDto): AuthResponseDto

    @POST("auth/refresh")
    suspend fun refresh(@Body body: RefreshRequestDto): AuthResponseDto

    @POST("auth/logout")
    suspend fun signOut()
}
