package app.kehdo.core.ui.theme

import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

/**
 * The Aurora palette.
 *
 * !!! GENERATED FROM /design/tokens/colors.json !!!
 *
 * To update: edit the JSON, then run `./tools/generate-tokens.sh`.
 * Do not edit this file by hand — your changes will be overwritten.
 *
 * (This is a hand-written placeholder for the scaffold; once the generator
 * is wired up in Phase 0 it will overwrite the contents.)
 */
object AuroraColors {
    val Canvas = Color(0xFF0A0612)
    val Surface = Color(0xFF1A0F2E)
    val SurfaceElevated = Color(0xFF24173D)

    val Purple = Color(0xFF9C5BFF)
    val PurpleBright = Color(0xFFB47BFF)
    val PurpleDeep = Color(0xFF6B2FD9)

    val Pink = Color(0xFFEC4899)
    val Amber = Color(0xFFF59E0B)
    val Blue = Color(0xFF3B82F6)
    val Emerald = Color(0xFF10B981)

    val Text = Color(0xFFF5F3FF)
    val TextDim = Color(0xA6F5F3FF) // 0.65 alpha
    val TextMute = Color(0x73F5F3FF) // 0.45 alpha

    val Line = Color(0x14FFFFFF) // 0.08 alpha
    val LineStrong = Color(0x24FFFFFF) // 0.14 alpha

    /** The signature aurora gradient. */
    val GradientAurora = Brush.linearGradient(
        colorStops = arrayOf(
            0.0f to Purple,
            0.5f to Pink,
            1.0f to Amber
        )
    )
}
